language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

addons:
  apt:
    packages:
    - gfortran

# command to install dependencies
before_install:
  - pip install scipy
  - pip install xarray
  - pip install igrf12
  - pip install numpy
  - pip install pysat
  - pip install matplotlib
   - pip install netCDF4
  # Prepare modified sami2py install
  - cd ..
  - echo 'cloning sami2py'
  - git clone https://github.com/sami2py/sami2py.git >/dev/null
  - echo 'installing sami2py'
  - cd ./sami2py
  - git checkout develop
  # install sami2py
  - python setup.py install >/dev/null
install:
 - cd ../growin
 - python setup.py install
# command to run tests
script:
  - pytest
