language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install pickle
  - pip install scipy
  - pip install xarray
  - pip install igrf12
  - pip install numpy
  - pip install pysat
  - pip install sami2py
# command to run tests
script:
  - pytest
